version: '3.8'
services:
  mineru-test:
    build: .
#    image: ghcr.io/betterandbetterii/mineru-mq:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - '8006:8000'
    container_name: mineru-test
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=mineru_parse_queue
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mineru-rabbitmq
    hostname: my-rabbit
    ports:
      - "5672:5672"    # AMQP 端口
      - "15672:15672"  # 管理界面端口
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data:
