name: Docker Build Image-RabbitMQ

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clean up unnecessary large folders
      run: |
        # Delete unnecessary large folders
        sudo rm -rf /opt/hostedtoolcache
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/share/boost
        # Clean apt cache
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        # Show available disk space
        df -h
        
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --debug
        
    - name: Login to Aliyun Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./projects/rabbitmq
        file: ./projects/rabbitmq/Dockerfile
        push: true
        tags: ${{ vars.DOCKER_REGISTRY }}/${{vars.DOCKER_NAMESPACE}}/${{ vars.IMAGE_NAME }}:latest
        cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/${{vars.DOCKER_NAMESPACE}}/${{ vars.IMAGE_NAME }}:buildcache,image-manifest=true
        cache-to: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/${{vars.DOCKER_NAMESPACE}}/${{ vars.IMAGE_NAME }}:buildcache,mode=max,image-manifest=true
